package com.github.thiago_v_a.poo_2023_01.t18;

public class Main {
    public static void main(String[] args) {
        Partida partida = new Partida("Partida Imortal de Anderssen");

        Jogador brancas = new Jogador("Anderssen");
        Jogador negras = new Jogador("Kieseritzky");

        Peca peao = new Peca("Peao");
        Peca bispo = new Peca("Bispo");
        Peca torre = new Peca("Torre");
        Peca cavalo = new Peca("Cavalo");
        Peca rainha = new Peca("Rainha");
        Peca rei = new Peca("Rei");

        Posicao lance1Posicao = new Posicao("e2", "e4");
        Posicao lance2Posicao = new Posicao("e7", "e5");
        Posicao lance3Posicao = new Posicao("f2", "f4");
        Posicao lance4Posicao = new Posicao("e5", "f4");
        Posicao lance5Posicao = new Posicao("f1", "c4");
        Posicao lance6Posicao = new Posicao("d8", "h4");
        Posicao lance7Posicao = new Posicao("e1", "f1");
        Posicao lance8Posicao = new Posicao("b7", "b5");
        Posicao lance9Posicao = new Posicao("c4", "b5");
        Posicao lance10Posicao = new Posicao("g8", "f6");
        Posicao lance11Posicao = new Posicao("g1", "f3");
        Posicao lance12Posicao = new Posicao("h4", "h6");
        Posicao lance13Posicao = new Posicao("d2", "d3");
        Posicao lance14Posicao = new Posicao("f6", "h5");
        Posicao lance15Posicao = new Posicao("f3", "h4");
        Posicao lance16Posicao = new Posicao("h6", "g5");
        Posicao lance17Posicao = new Posicao("h4", "f5");
        Posicao lance18Posicao = new Posicao("c7", "c6");
        Posicao lance19Posicao = new Posicao("g2", "g4");
        Posicao lance20Posicao = new Posicao("h5", "f6");
        Posicao lance21Posicao = new Posicao("h1", "g1");
        Posicao lance22Posicao = new Posicao("c6", "b5");
        Posicao lance23Posicao = new Posicao("h2", "h4");
        Posicao lance24Posicao = new Posicao("g5", "g6");
        Posicao lance25Posicao = new Posicao("h4", "h5");
        Posicao lance26Posicao = new Posicao("g6", "g5");
        Posicao lance27Posicao = new Posicao("d1", "f3");
        Posicao lance28Posicao = new Posicao("f6", "g8");
        Posicao lance29Posicao = new Posicao("c1", "f4");
        Posicao lance30Posicao = new Posicao("g5", "f6");
        Posicao lance31Posicao = new Posicao("b1", "c3");
        Posicao lance32Posicao = new Posicao("f8", "c5");
        Posicao lance33Posicao = new Posicao("c3", "d5");
        Posicao lance34Posicao = new Posicao("f6", "b2");
        Posicao lance35Posicao = new Posicao("f4", "d6");
        Posicao lance36Posicao = new Posicao("c5", "g1");
        Posicao lance37Posicao = new Posicao("e4", "e5");
        Posicao lance38Posicao = new Posicao("b2", "a1");
        Posicao lance39Posicao = new Posicao("f1", "e2");
        Posicao lance40Posicao = new Posicao("b8", "a6");
        Posicao lance41Posicao = new Posicao("f5", "g7");
        Posicao lance42Posicao = new Posicao("e8", "d8");
        Posicao lance43Posicao = new Posicao("f3", "f6");
        Posicao lance44Posicao = new Posicao("g8", "f6");
        Posicao lance45Posicao = new Posicao("d6", "e7");


        Lance lance1 = new Lance(brancas, peao, lance1Posicao);
        Lance lance2 = new Lance(negras, peao, lance2Posicao);
        Lance lance3 = new Lance(brancas, peao, lance3Posicao);
        Lance lance4 = new Lance(negras, peao, lance4Posicao);
        Lance lance5 = new Lance(brancas, bispo, lance5Posicao);
        Lance lance6 = new Lance(negras, rainha, lance6Posicao);
        Lance lance7 = new Lance(brancas, rei, lance7Posicao);
        Lance lance8 = new Lance(negras, peao, lance8Posicao);
        Lance lance9 = new Lance(brancas, bispo, lance9Posicao);
        Lance lance10 = new Lance(negras, cavalo, lance10Posicao);
        Lance lance11 = new Lance(brancas, cavalo, lance11Posicao);
        Lance lance12 = new Lance(negras, rainha, lance12Posicao);
        Lance lance13 = new Lance(brancas, peao, lance13Posicao);
        Lance lance14 = new Lance(negras, cavalo, lance14Posicao);
        Lance lance15 = new Lance(brancas, cavalo, lance15Posicao);
        Lance lance16 = new Lance(negras, rainha, lance16Posicao);
        Lance lance17 = new Lance(brancas, cavalo, lance17Posicao);
        Lance lance18 = new Lance(negras, peao, lance18Posicao);
        Lance lance19 = new Lance(brancas, peao, lance19Posicao);
        Lance lance20 = new Lance(negras, cavalo, lance20Posicao);
        Lance lance21 = new Lance(brancas, torre, lance21Posicao);
        Lance lance22 = new Lance(negras, peao, lance22Posicao);
        Lance lance23 = new Lance(brancas, peao, lance21Posicao);
        Lance lance24 = new Lance(negras, rainha, lance22Posicao);
        Lance lance25 = new Lance(brancas, peao, lance21Posicao);
        Lance lance26 = new Lance(negras, rainha, lance22Posicao);
        Lance lance27 = new Lance(brancas, rainha, lance21Posicao);
        Lance lance28 = new Lance(negras, cavalo, lance22Posicao);
        Lance lance29 = new Lance(brancas, bispo, lance21Posicao);
        Lance lance30 = new Lance(negras, rainha, lance22Posicao);
        Lance lance31 = new Lance(brancas, cavalo, lance21Posicao);
        Lance lance32 = new Lance(negras, bispo, lance22Posicao);
        Lance lance33 = new Lance(brancas, cavalo, lance21Posicao);
        Lance lance34 = new Lance(negras, rainha, lance22Posicao);
        Lance lance35 = new Lance(brancas, bispo, lance21Posicao);
        Lance lance36 = new Lance(negras, bispo, lance22Posicao);
        Lance lance37 = new Lance(brancas, peao, lance21Posicao);
        Lance lance38 = new Lance(negras, rainha, lance22Posicao);
        Lance lance39 = new Lance(brancas, rei, lance21Posicao);
        Lance lance40 = new Lance(negras, cavalo, lance22Posicao);
        Lance lance41 = new Lance(brancas, cavalo, lance21Posicao);
        Lance lance42 = new Lance(negras, rei, lance22Posicao);
        Lance lance43 = new Lance(brancas, rainha, lance21Posicao);
        Lance lance44 = new Lance(negras, cavalo, lance22Posicao);
        Lance lance45 = new Lance(brancas, bispo, lance21Posicao);

        partida.adicionarLance(lance1);
        partida.adicionarLance(lance2);
        partida.adicionarLance(lance3);
        partida.adicionarLance(lance4);
        partida.adicionarLance(lance5);
        partida.adicionarLance(lance6);
        partida.adicionarLance(lance7);
        partida.adicionarLance(lance8);
        partida.adicionarLance(lance9);
        partida.adicionarLance(lance10);
        partida.adicionarLance(lance11);
        partida.adicionarLance(lance12);
        partida.adicionarLance(lance13);
        partida.adicionarLance(lance14);
        partida.adicionarLance(lance15);
        partida.adicionarLance(lance16);
        partida.adicionarLance(lance17);
        partida.adicionarLance(lance18);
        partida.adicionarLance(lance19);
        partida.adicionarLance(lance20);
        partida.adicionarLance(lance21);
        partida.adicionarLance(lance22);
        partida.adicionarLance(lance23);
        partida.adicionarLance(lance24);
        partida.adicionarLance(lance25);
        partida.adicionarLance(lance26);
        partida.adicionarLance(lance27);
        partida.adicionarLance(lance28);
        partida.adicionarLance(lance29);
        partida.adicionarLance(lance30);
        partida.adicionarLance(lance31);
        partida.adicionarLance(lance32);
        partida.adicionarLance(lance33);
        partida.adicionarLance(lance34);
        partida.adicionarLance(lance35);
        partida.adicionarLance(lance36);
        partida.adicionarLance(lance37);
        partida.adicionarLance(lance38);
        partida.adicionarLance(lance39);
        partida.adicionarLance(lance40);
        partida.adicionarLance(lance41);
        partida.adicionarLance(lance42);
        partida.adicionarLance(lance43);
        partida.adicionarLance(lance44);
        partida.adicionarLance(lance45);



        partida.imprimirLances();
    }
}
